tests/vm_nesting.sh
Follow up on https://github.com/canonical/lxd/pull/11993
=> tests: Add suite for VM nesting scenarios

tests/network-routed
=> tests/network-routed: More tweaks to try and get working in Canonical's runners

tests/network-ovn
This was successfully ran on PS5.
=> Refresh `network-ovn` and make it work without IPv6

tests/network, tests/network-ovn
There's more work to do here, but this is a start...
=> tests: network-ovn improvements

tests/vm_nesting.sh
=> tests/vm_nesting: Reworks to be consistent with other scripts

tests/network-ovn
It's still not perfect but seems to be a bit more reliable
=> network-ovn: improve reliability

tests/network-bridge-firewall
Test for https://github.com/canonical/lxd/pull/12135
=> tests/network-bridge-firewall: add limits.priority test for nftables

tests/cgroup
From https://github.com/lxc/lxc-ci/pull/791
=> cgroup: Fix ingress test

tests/storage-vm
Addition to https://github.com/canonical/lxd/pull/12632 in order to test copying instances with snapshots.
=> Add copying of VMs with snapshots

README.md, bin/helpers, tests/cgroup, tests/devlxd-vm, tests/gpu-container, tests/interception, tests/network, tests/network-bridge-firewall, tests/network-ovn, tests/rbac, tests/storage-volumes-vm
@tomponline this should make repeated test runs faster but I would like your input regarding the purging of the LXD snap? See the `bin/helpers: make repeated runs faster if PURGE_LXD is exported` commit.
=> Faster repeated runs

bin/openstack-run, bin/testflinger-run, tests/docker, tests/main-openstack, tests/network-ovn
Also follow-up on suggestions in #58 and minor tweaks to `tests/docker`.
=> Allow overriding the TEST_IMG when running openstack/testflinger

bin/helpers, bin/local-run, bin/openstack-run, bin/testflinger-run, tests/network-ovn
This addresses the test weakness related to #63 but doesn't address the root cause.
=> tests/network-ovn: make sure `network acl show-log` returns some content

.github/workflows/tests.yml, tests/efi-vars-editor-vm, tests/main-openstack, tests/main-testflinger
Depends on:
https://github.com/canonical/lxd/pull/12870
=> tests/efi-vars-editor-vm: add a new test

tests/storage-vm
Related to https://github.com/canonical/lxd/pull/12938
=> Test volume.block.filesystem ignore

tests/storage-vm
Requires https://github.com/canonical/lxd/pull/12832
=> tests: Check `instances.migration.stateful` effect on VMs' `migration.stateful` parameter

tests/storage-vm
Check the `instances_migration_stateful` API extension
=> tests/storage-vm: check the `instances_migration_stateful` API extension before running associated test

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml, .github/workflows/images.yml, bin/test-image
Virtual machine tests for built images are too slow on self hosted runners.
=> Revert: Run image builds on self hosted runners

.github/workflows/tests.yml, tests/devlxd-vm, tests/storage-vm
Include 2 small tweaks to `tests/storage-vm` while at it, one inspired by #102
=> Run tests against `5.21/edge`

.github/actions/image-upload/action.yml, .github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml, bin/build-distro
This PR enables image publishing.
=> Publish images after successful build

.github/actions/image-upload/action.yml, .github/workflows/image-alpine.yml
Revert debug changes from https://github.com/canonical/lxd-ci/pull/109
=> Revert tmate and debug output

images/alpine.yaml, images/amazonlinux.yaml, images/archlinux.yaml, images/centos.yaml, images/debian.yaml, images/gentoo.yaml, images/nixos.yaml, images/oracle.yaml, images/springdalelinux.yaml, images/ubuntu.yaml
Add simplestream configuration for image requirements and release aliases.
=> images: Add simplestream configuration

.github/workflows/image-slackware.yml, images/slackware.yaml
This is only for the `current` version of Slackware.
Version `15.0` does not build, so there will be a follow up when I manage to get it working.
=> Add slackware image build

bin/helpers, tests/cluster
Follow up on https://github.com/canonical/lxd-ci/pull/116 (https://github.com/canonical/lxd-ci/pull/125).
=> Test: Cert checks followup

tests/interception
https://github.com/canonical/lxd/pull/13151
=> tests/interception: add test for finit_module interception

.github/workflows/image-alpine.yml
Fix in matrix. Each field should be an array.
=> Fix Alpine image build matrix

.github/actions/image-setup/action.yml
=> image-setup: Fix typo in list of apt packages

tests/storage-disks-vm
See https://github.com/canonical/lxd/pull/13332
=> storage-disks-vm: add a few extra tests for raw.idmap setting

.github/actions/image-setup/action.yml, .github/workflows/image-fedora.yml, bin/test-image
I added a few small things while waiting for the local test build :)
=> github/workflow: Add Fedora 40

tests/cgroup, tests/cluster, tests/container-copy, tests/cpu-vm, tests/devlxd-vm, tests/docker, tests/efi-vars-editor-vm, tests/gpu-container, tests/gpu-mig, tests/gpu-vm, tests/interception, tests/network, tests/network-bridge-firewall, tests/network-ovn, tests/network-routed, tests/network-sriov, tests/storage-buckets, tests/storage-disks-vm, tests/storage-vm, tests/storage-volumes-vm, tests/vm-nesting
While at it, cleanup how the per-script test image is defined.
=> `s/22.04/24.04`

.github/workflows/image-alpine.yml
Simplification of exclude as mention in comment https://github.com/canonical/lxd-ci/pull/154#discussion_r1572542203
I'm changing only for Alpine to test it first.
=> images: Remove exclude in matrix (Alpine)

.github/workflows/image-almalinux.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-voidlinux.yml
Follow up on https://github.com/canonical/lxd-ci/pull/160 for all other architectures beside Alpine
=> images: Determine image architecture based on a schedule

tests/container-copy
Fixes https://github.com/canonical/lxd/issues/13388
=> tests/container-copy: allow some time for the VM time to stabilize

.github/workflows/image-rockylinux.yml
This was reported by one of our user: https://discourse.ubuntu.com/t/lack-od-rocky-linux/45263?u=sdeziel1
=> github: fix typo in rockylinux.yml

bin/tf-reserve
some minor changes to `bin/tf-reserve`
=> Update testflinger reserve function

images/fedora.yaml, images/funtoo.yaml
Messing with funtoo package list results in builds taking over half an hour. 
Changes tested both locally and on forked GH actions:
- Funtoo: https://github.com/MusicDin/lxd-ci/actions/runs/9515513192
- Fedora: https://github.com/MusicDin/lxd-ci/actions/runs/9515514532
=> images: Fedora and Funtoo

.github/workflows/image-nixos.yml
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/9515827695
=> Enable NixOS 24.05 builds

.github/workflows/image-ubuntu.yml, images/ubuntu.yaml
This should just be a cleanup with no visible side-effect.
=> Update Ubuntu workflow/image

images/archlinux.yaml
Should fix https://github.com/canonical/lxd-ci/actions/runs/9688390234/job/26734859244#step:7:79
=> Fix archlinux images to pass `systemd --failed` test

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml, .github/workflows/testflinger-submit.yml, .github/workflows/tests.yml
Fixes linter issues in `.github/workflows` (inline comment spacing and identation)
=> Fix yaml linting issues

images/debian.yaml
(cherry picked from commit e279a8fc33575247ec6c322591ce4da2e43b1fde)
=> debian: Switch to installing pkexec

tests/gpu-container, tests/gpu-mig, tests/maas, tests/storage-volumes-vm
=> tests: Always use lxc stop -f (force)

.github/workflows/tests.yml, tests/qemu-external-vm
test for https://github.com/canonical/lxd/pull/13742
=> Qemu external snap test

.github/workflows/tests.yml, tests/vm-migration
This will fail until https://github.com/canonical/lxd/pull/13823 is merged.
=> Add tests for VM live migration with volumes attached (ceph)

.github/workflows/tests.yml
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2064508 is fixed
=> test/cluster: reinstate test on 24.04

images/gentoo.yaml
Cherry-picked from https://github.com/lxc/lxc-ci/pull/837
Passing workflow: https://github.com/MusicDin/lxd-ci/actions/runs/10269082357/job/28413694431
=> images/gentoo: Remove GPG workaround and update packages

.github/workflows/image-ubuntu.yml, images/ubuntu.yaml
https://lists.ubuntu.com/archives/ubuntu-security-announce/2024-July/008463.html
=> Drop Ubuntu Mantic (EOL)

images/almalinux.yaml, images/archlinux.yaml, images/centos.yaml, images/fedora.yaml, images/openeuler.yaml, images/opensuse.yaml, images/rockylinux.yaml, images/springdalelinux.yaml, tests/storage-disks-vm
Adds tests for canonical/lxd#13905
=> tests/storage-disks-vm: Add tests for virtio-blk and virtio-scsi

tests/storage-buckets, tests/storage-vm
Test for https://github.com/canonical/lxd-pkg-snap/pull/413
=> tests/storage-vm: add test for snap zfs.external

tests/network-ovn
See https://github.com/canonical/lxd/pull/13900
=> tests/network-ovn: Fix tests for long-lived ports

tests/container
https://github.com/canonical/lxd/commit/aebc412682916842c6be51ecff33c40d2d1fbb79
=> tests/container: add check for sysfs mount

tests/gpu-container, tests/igpu-container
related to: https://github.com/canonical/lxd/pull/13562
=> Add iGPU passthrough test for container

images/ubuntu.yaml
Closes https://github.com/canonical/lxd/issues/13773
=> images: Prevent screen lock on Ubuntu desktop images

news/weekly-changes.sh
Add dedicated sections for PyLXD (https://github.com/canonical/pylxd) and LXD Terraform provider (https://github.com/terraform-lxd/terraform-provider-lxd/) in LXD weekly news.
=> news: Add sections for PyLXD and LXD Terraform provider

tests/conversion
After chatting about #292 with @MusicDin he mentioned that I forgot about this other case.
=> tests/conversion: conserve CPU/disk by exporting to stdout

tests/network-bridge-firewall
See https://github.com/canonical/lxd/pull/14279
=> Firewall: Add NAT checks

tests/network-bridge-firewall, tests/network-ovn
tests for https://github.com/canonical/lxd/pull/14276
=> tests/network-(bridge-firewall|ovn): add IPv6 CIDR size checks tests

tests/storage-vm
Workaround for https://bugs.launchpad.net/snapd/+bug/2028141 and https://bugs.launchpad.net/snapd/+bug/2083961
=> tests/storage-vm: replace snap restart by systemctl restart

tests/cluster
Fixes commit 7b4d06a2ca476cd21df89b04e3ee35a0bbf51d91
=> tests/cluster: fix wrong comparison

.github/workflows/tests.yml
Currently its not possible to run the CI for different tracks concurrently.
=> Concurrency fixes

images/almalinux.yaml
=> images/almalinux: Fix almalinux mirror

images/openwrt.yaml
Just follow up on https://github.com/canonical/lxd-ci/pull/359
=> images/openwrt: Install sudo on snapshot release

tests/conversion
Avoiding the 2 go snap installation should shave ~1m15s.
=> Make `tests/conversion` a bit faster

.github/workflows/tests.yml, README.md, bin/helpers, bin/local-run, tests/network-ovn, tests/vm-migration
=> Test against both MicroOVN and OVN debs

README.md
Revert the initial idea and document the actual behavior.
=> Doc: Clarify the use of the right PowerFlex storage pool

.github/workflows/tests.yml, tests/cloud-init
This includes the tests for `cloud-init.ssh-keys`
=> tests: Introduce cloud-init tests

.github/actions/set-aproxy-bypass-for-testflinger/action.yml, .github/workflows/nvidia-test.yml, .github/workflows/testflinger-submit.yml, .github/workflows/testflinger/README.md, .github/workflows/testflinger/run.sh, .github/workflows/testflinger/uc-nvidia-job.yml
Inspired by [1] and Michał Sawicz's Testflinger job published in Canonical MM.
[1] https://github.com/canonical/docker-snap/blob/d28b3d427d5d5fe6c7bffbcf160d8ad9de849419/.github/workflows/nvidia-test.yml#L1
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
=> github: add NVIDIA tests on Ubuntu Core

tests/storage-disks-vm
Adapts tests to https://github.com/canonical/lxd/pull/15225
=> tests/storage-disks-vm: Update device symlink test

images/debian.yaml
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1103503
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1104344
=> images/debian: workaround debian bugs causing apparmor failures

README.md
This should help us quickly identify which job requires our attention.
=> README: add CI badges

images/openwrt.yaml
(cherry picked from commit 11253491d846abdca51fc04c7907f080f781c845)
License: Apache-2.0
=> images/openwrt: Add ula_prefix to network config

images/openwrt.yaml
Fixes https://github.com/canonical/lxd/issues/15321
=> images/openwrt: Remove arch condition

.github/workflows/image-alpine.yml
https://alpinelinux.org/releases/
=> github: Alpine 3.18 is now EOL

.github/workflows/tests.yml, bin/helpers, tests/container, tests/lxd-installer
Verify that `ubuntu-daily:` and `ubuntu-minimal-daily:` images have
`lxd-installer` installed and working properly.
Also verify the resulting LXD snap works with ZFS when installed inside VMs.
Closes https://github.com/canonical/lxd/issues/14421
=> tests/lxd-installer: new test

bin/local-run, tests/cgroup, tests/network-ovn
Also ensure the minimum `set -eu` options are always used too.
=> bin/local-run: execute test script with pipefail

bin/helpers, tests/network-ovn
Also, reduce noise from `hasNeededAPIExtension()`.
=> Drop unneeded false clauses

.github/workflows/testflinger/README.md, .github/workflows/testflinger/run.sh
- Fix job reference in run.sh
- Add testflinger-cli install step in README
=> testflinger: Minor fixes

tests/ui
* tests/ui: use ui latest test suite for the 6 snap channels
=> tests/ui: use ui latest test suite for the 6 snap channels

.github/workflows/testflinger/README.md, .github/workflows/testflinger/run.sh, .github/workflows/testflinger/uc-nvidia-cdi-job.yml
- update NVIDIA driver version
- add some extra debugging prints
- add an extra sleep to ensure that machine restarts after kernel upgrade
=> workflows/testflinger: update NVIDIA tests

tests/storage-volumes-vm
=> tests/storage-volumes-vm: Format if condition
