bin/openstack-run
On PS5, the flavors, networks are named differently so look them up. I couldn't do a full test run because on PS5, the bastion isn't automatically allowed to reach the VMs. The missing firewall change for that bit is on its way though.
=> Compatibility with PS5 env

tests/cpu-vm, tests/devlxd-vm, tests/docker, tests/network, tests/network-routed, tests/network-sriov, tests/storage-disks-vm, tests/storage-vm, tests/storage-volumes-vm
The old debs are no longer installed on Focal+ so
there is no need to try to remove them.
cloud-init causes no harm and can be used in some env.
=> tests/*: stop purging old debs and keep cloud-init

bin/openstack-run, tests/kernel
This test requires access to https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/daily which isn't (yet) accessible from PS5/6 so I couldn't test it.
Once we have proxy access, I'll look into adding it to `test/main.sh` list.
=> Update `test/kernel` script

tests/network
This PR switches to using cloud-init with a `write_files` statement that sets up a per-boot script that sets the instance's state to READY via curl to /dev/lxd.
It then introduces a `waitInstanceReady` helper to wait until the instance reaches the known READY state.
=> tests: Improve network test reliability

.github/workflows/commits.yml, tests/network-ovn
The DCO and branch target jobs were merged together.
=> `network-ovn` add tests for instance and ACL names starting with a digit

tests/network-ovn
This PR adds a test for OVN leases to ensure leases are not disappearing from the output of the `lxc network list-leases <ovn_network>`.
Related to:
- https://github.com/canonical/lxd/pull/12236
- https://github.com/canonical/lxd/pull/12311
=> Add test for OVN network leases

tests/network-ovn
The main issue was due to the `testovn` project using a dedicated set of profiles thus not having the cloud-init `curl Ready | /dev/lxd` bits applied from the default profile.
My use of a custom image based on `ubuntu-minimal:22.04` papered over this by forcing the `curl Ready | /dev/lxd` bits to be in the base image making it magically way faster :)
=> network-ovn: revert to using ubuntu:22.04

bin/openstack-run, tests/main.sh, tests/storage-disks-vm
This is the output of the test running on PS6:
```
+ lxc stop -f v1
+ lxc config device remove v1 d1
Device d1 removed from v1
+ lxc project unset restricted restricted.devices.disk
+ lxc project unset restricted restricted.devices.disk.paths
+ lxc project unset restricted restricted
+ lxc config device add v1 nvme-ssd disk source=/dev/loop4 io.bus=nvme
Device nvme-ssd added to v1
+ lxc start v1
+ waitVMAgent v1
+ set +x
+ + grep -F QEMU NVM Express Controller
lxc exec v1 -- lspci
06:00.0 Non-Volatile memory controller: Red Hat, Inc. QEMU NVM Express Controller (rev 02)
==> Cleanup
+ echo ==> Cleanup
+ lxc delete -f v1
+ lxc project switch default
+ lxc project delete restricted
Project restricted deleted
+ lxc storage delete default
Storage pool default deleted
+ lxc network delete …
```
=> Add NVMe test to `tests/storage-disks-vm`

bin/custom-kernel, bin/helpers, bin/openstack-run, tests/cgroup, tests/gpu-container, tests/interception, tests/main.sh, tests/network-bridge-firewall, tests/pylxd, tests/storage-disks-vm
The helper functions are moved to a single script snippet (`bin/helpers`) that is inserted along with the LXD snap channel to for a given test. This should make it easy to reuse when we add a different runner (`lxd-run`) alongside of `bin/openstack-run`.
The `tests/main.sh` metascript contains what was successfully tested on PS6. So ATM, the few tests we have are all passing on `latest/edge` and `5.0/edge`. The bits that are not working on `5.0/edge` as skipped thanks to API extension detection, same for minimum kernel requirements.
Note: the `tests/interception` doesn't work on `5.0/edge` but I'm wondering if that's because I'm using the wrong extensions to gate the mount tests?
```
$ ./bin/openstack-run jammy default tests/interception "5.0/edge"
...
+ hasNeededAPIExtension …
```
=> Helper functions

bin/helpers, tests/cgroup, tests/cpu-vm, tests/devlxd-vm, tests/network, tests/network-ovn, tests/network-routed, tests/network-sriov, tests/storage-disks-vm, tests/storage-vm, tests/storage-volumes-vm
`waitInstanceReady()`: used to wait for the instance to report a processes count greater than 1
`waitInstanceBooted()`: used to wait for the instance be fully booted
@tomponline for `waitInstanceBooted()`, I couldn't find a way around the `Failed to connect to bus: No such file or directory` issue you ran into so I added a `sleep 1` :/ At least it worked twice without running into that specific issue.
While in there, also add a workaround for https://github.com/canonical/lxd/issues/12659 in `tests/cgroup` and mark the test as incompatible with `-kvm` kernel flavor.
=> Rework helper functions to wait for instance readiness

bin/helpers, bin/testflinger-run, tests/gpu-container
This was tested on `rockman` using:
```
PURGE_LXD=1 ./bin/local-run tests/gpu-container latest/edge
```
`rockman` has the particularity of having 3 GPUs, one onboard Matrox and 2x NVIDIA L40.
=> Make `tests/gpu-container` adapt to available HW

tests/gpu-container
Based on comments/suggestion from https://github.com/canonical/lxd-ci/pull/50#issuecomment-1858451719
@escabo, this addresses your feedback  however I couldn't find a nice way to avoid DKMS triggering the onboarding of custom MOKs and thus prompting for password. The test will warn and bail if secureboot is enabled.
@tomponline this was tested successfully on `rockman`.
=> Improve `tests/gpu-container` to pick the recommended driver series and abort on secureboot enabled

tests/gpu-mig
This test was validated on `torchtusk` that has 2 NVIDIA A100:
```
root@torchtusk:~# nvidia-smi -L
GPU 0: NVIDIA A100-PCIE-40GB (UUID: GPU-2a956425-8ac7-bb38-eb07-be255e4fe341)
GPU 1: NVIDIA A100-PCIE-40GB (UUID: GPU-098f2285-d2d8-d51c-5e7e-bf3724b250a3)
```
Due to having 2 identical cards, I had to change disable one of the test (`vendorid`/`productid`) and simply assign multiple MIG devices to the container.
This was tested successfully against `5.0/edge` and `latest/edge`.
=> Polish `tests/gpu-mig` test

tests/main-testflinger, tests/network-sriov
The test now tries to pick the first SR-IOV capable NIC if none was provided. This allows automatic testing through `testflinger` on `luma`. There unfortunately, IPv6 is not enabled so I had to make the script warn instead of hard failing.
Also, since we are close to having `24.04`, I opted to switch the VMs from `23.10` to `24.04` as it works with it as well.
This was tested successfully with `5.0/edge` and `latest/edge`.
=> Polish `tests/network-sriov` test

tests/cgroup, tests/cluster, tests/cpu-vm, tests/devlxd-vm, tests/docker, tests/gpu-container, tests/gpu-mig, tests/gpu-vm, tests/interception, tests/main-testflinger, tests/network, tests/network-bridge-firewall, tests/network-ovn, tests/network-routed, tests/network-sriov, tests/rbac, tests/storage-disks-vm, tests/storage-vm, tests/storage-volumes-vm, tests/vm-nesting
This should be merged after #54.
This was tested successfully with:
```
PURGE_LXD=1 ./bin/local-run tests/cluster 5.0/edge 3 5.0/stable 5.0/edge
PURGE_LXD=1 ./bin/local-run tests/cluster latest/edge 3 latest/stable latest/edge
```
So upgrading `5.0/stable` -> `5.0/edge` and `latest/stable` -> `latest/edge`.
=> Enable `tests/cluster` test

tests/storage-vm
In addition to https://github.com/canonical/lxd/pull/12777
=> Add restore check for VM's filesystem volume

bin/helpers, bin/openstack-run, bin/testflinger-run, tests/cgroup, tests/cluster, tests/devlxd-vm, tests/docker, tests/main-openstack, tests/main-testflinger, tests/network, tests/network-ovn, tests/storage-vm, tests/storage-volumes-vm, tests/vm-nesting
Many small fixes with the most interesting parts being in `tests/network-ovn` where the workaround for 
https://github.com/ovn-org/ovn/issues/124 was updated to be IPv6 only (IPv4 now works). For some reason, ICMP doesn't go through but TCP does which seems in line with that `ovn-nbctl` reports:
```
Network forward 192.0.2.1 created
_uuid               : 2610499d-ca24-4ddc-bb3e-d710cb572621
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net22-lb-192.0.2.1-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"192.0.2.1"="10.105.175.2"}
```
Is this an OVN regression or simply that LXD doesn't provided the needed protocol list?
Of note, the `tests/docker` script was changed to not depend …
=> Misc fixes

bin/openstack-run, tests/storage-volumes-vm
`hasNeededAPIExtension` checks the LXD extension list so using it prior to `install_lxd` will not work reliably. This package being ~370KiB, let's just always install it.
=> tests/storage-volumes-vm: always install genisoimage

README.md, bin/helpers, tests/storage-vm, tests/storage-volumes-vm
This PR adapts both of the VM storage tests so they can be executed using the Dell PowerFlex storage driver from https://github.com/canonical/lxd/pull/12304.
Storage size values for PowerFlex need to be in multiples of 8GiB. The minimal storage volume size in PowerFlex is also 8GiB. 
Where applicable the storage size of the actual test was increased for all the drivers to accommodate PowerFlex. At other places a different storage size gets set for the PowerFlex driver only.
=> Adapt VM storage tests to support Dell PowerFlex

tests/storage-buckets
As MinIO is no longer bundled with LXD, we have to build it manually for the tests and set `minio.path` on the LXD snap.
=> Install and remove MinIO for storage buckets tests

bin/custom-kernel
```
root@v1:~/lxd-ci# ./bin/custom-kernel daily
===> Installing a mainline daily build
...
Generating grub configuration file ...
GRUB_FORCE_PARTUUID is set, will attempt initrdless boot
Found linux image: /boot/vmlinuz-6.8.0-060800rc5daily20240221-generic
Found initrd image: /boot/initrd.img-6.8.0-060800rc5daily20240221-generic
Found linux image: /boot/vmlinuz-5.15.0-1049-kvm
Found initrd image: /boot/initrd.img-5.15.0-1049-kvm
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
Adding boot menu entry for UEFI Firmware Settings ...
done
root@v1:~/lxd-ci# 
Session terminated, killing shell...
...killed.
```
Then after the reboot we have the latest …
=> Improve `custom-kernel`

.github/workflows/tests.yml, tests/container-copy, tests/main-openstack, tests/main-testflinger
Adds a test to catch snap-specific regressions in rsync, prompted by https://github.com/canonical/lxd/pull/12927
Should be merged after https://github.com/canonical/lxd/pull/12927
=> Test container copy from external mounted storage

.github/workflows/tests.yml, bin/helpers, tests/cluster
* use `--quiet` when getting a cluster join token instead of discarding the first line of text
* `extra_cleanup()` now always execute and will halt on error behavior as we want to make sure cleanup steps do work
* only do the "reclaim space" step for storage tests.
The "reclaim space" step can take anywhere between 10s to ~2m depending if we get a fast or slow GHA runner. We only need the extra space for the `tests/storage-*` script so only run it then.
=> Small improvements

.github/workflows/tests.yml
This fixes the some rare occurrences of:
```
++ findmnt --noheading --type ext4 --list --uniq
++ awk '{print $1}'
+ for fs in $(findmnt --noheading --type ext4 --list --uniq | awk '{print $1}')
+ sudo mount -o remount,noatime,barrier=0,commit=6000 /
+ for fs in $(findmnt --noheading --type ext4 --list --uniq | awk '{print $1}')
+ sudo mount -o remount,noatime,barrier=0,commit=6000 /mnt
+ for fs in $(findmnt --noheading --type ext4 --list --uniq | awk '{print $1}')
+ sudo mount -o remount,noatime,barrier=0,commit=6000 /var/lib/containers/storage/overlay
mount: /var/lib/containers/storage/overlay: mount point not mounted or bad option.
```
=> Remove more container runtimes from GitHub runners

tests/storage-vm
In case of `instances.migration.stateful=false`, since `migration.stateful` is `false` by default if nothing is manually set for an instance, no need to make `migration.stateful=false` appear in the configuration. It is unset instead, which means the same.
=> tests/storage-vm: if `instances.migration.stateful=false` do not change `migration.stateful`

.github/workflows/tests.yml, tests/interception
I did a bit of cleanup and enabled `tests/interception` on `5.0/*` as it works there and I couldn't remember why I decided to exclude it.
=> Configurable snap tracks

.github/workflows/image-debian.yml, bin/helpers, bin/test-image
Wait for instance to be ready when testing image builds instead of waiting for a fixed time.
We will see whether this approach will cause any significant issues.
Also this PR disables Debian Sid builds (for now).
=> Wait instance to be ready

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml, .github/workflows/images.yml
This should run image builds on the self-hosted runners. 
I've temporary disabled the majority of image builds to not waste the resources in case something goes wrong.
I'm not sure if `focal` runners are available, as those could be required for certain images (such as Orcale and AmazonLinux) if jammy ones do not support cgroups v1.
=> Run image builds on self-hosted runners

.github/workflows/tests.yml, bin/helpers, tests/cgroup, tests/cluster, tests/container-copy, tests/efi-vars-editor-vm, tests/gpu-container, tests/gpu-mig, tests/network-ovn, tests/storage-volumes-vm, tests/vm-nesting
This `extra_cleanup()` idea was a bad one. We want cleanup steps to run on successful runs and any failure during cleanup should cause a test failure anyway.
=> Remove `extra_cleanup()`

bin/test-image
Image build tests are currently failing because `large` self-hosted runners have only 2 CPUs and we cannot allocate more CPUs than available to the VM.
I would prefer not use larger runners (`xlarge`), since there are only 10 available.
=> Remove VM cpu limit in image tests

tests/efi-vars-editor-vm
Attempt to fix:
https://github.com/canonical/lxd-ci/actions/runs/8200639198/job/22427798532?pr=99
```
+ echo '==> Try to set EFI variable while VM is running (should fail)'
+ lxc config uefi set v1 testvar-8be4df61-93ca-11d2-aa0d-00e098032b8c=48656c6c6f2066726f6d204c5844
Error: UEFI variables editing is allowed for stopped VM instances only
+ lxc stop -f v1
+ echo '==> Try to set invalid data as EFI variable value'
==> Try to set invalid data as EFI variable value
+ lxc config uefi set v1 testvar-8be4df61-93ca-11d2-aa0d-00e098032b8c=0
Error: Failed to run: uefivars.py -o json -i edk2: exit status 1 (Reading uefivars from stdin
Traceback (most recent call last):
File "/snap/lxd/27513/bin/uefivars.py", line 8, in <module>
sys.exit(main())
File …
```
=> efi-vars-editor-vm: add wait for instance to be ready

tests/network-ovn
See https://github.com/canonical/lxd/issues/13069
The OVN tests still dont pass but they fail on the ACL show-log command being fixed by https://github.com/canonical/lxd/pull/13060 but they no longer fail on the peering tests.
=> tests/network-ovn: Add workaround for peering test on GHA Azure kernel

tests/cpu-vm
...and allow them in profiles. I chose not to go with @simondeziel's suggestion to use `--empty` as the tests fit well enough in `cpu-vm`, but I'm happy to spin up a new test if needed.
Resolves https://github.com/canonical/lxd/pull/13051
=> tests/cpu-vm: reject `limits.kernel.*` for VMs

tests/storage-vm
I figure it's worth running through `Driver.Update` even if it won't catch all the corner cases (e.g. canonical/lxd#13038).
https://github.com/canonical/lxd/pull/13101 for context.
=> tests/storage-vm: Test pool resize for zfs and btrfs

tests/storage-vm
This is related to the bug https://github.com/canonical/lxd/issues/13085.
=> tests/storage-vm: Temporarily exclude local refresh on Btrfs

tests/cluster
This should address failures of the `tests/cluster` suite in case snapd isn't yet ready. This happened in one of the pipelines e.g. https://github.com/canonical/lxd-ci/actions/runs/8261572982/job/22599147506?pr=103. 
The same is done in the `tests/vm-nesting` suite: https://github.com/canonical/lxd-ci/blob/main/tests/vm-nesting#L89
=> tests/cluster: Wait until snapd is seeded

tests/storage-vm
The refresh got fixed in https://github.com/canonical/lxd/pull/13133.
=> Tests: Revert the Btrfs refresh exception

tests/cgroup
https://github.com/canonical/lxd/pull/13192
=> tests/cgroup: check cgroup.max/cgroup.high values

.github/workflows/image-fedora.yml
=> github/workflow: Drop Fedora 37

.github/actions/image-upload/action.yml
SCP flag `-s` (*Use the SFTP protocol for transfers rather than the original scp protocol.*) is not supported on older runners (specifically 20.04), therefore, use SFTP client for file transfer.
=> Use SFTP instead of SCP to upload images

.github/workflows/image-oracle.yml
This PR just fixes the upload for oracle images.
Seems I've missed that one when updating actions in https://github.com/canonical/lxd-ci/pull/108.
=> Fix upload of Oracle images

.github/actions/image-upload/action.yml
Upload contents of the built image to the temporary dir and only once fully uploaded move the directory to the final destination to avoid making partially uploaded images available in the simplestream index.
Closes https://github.com/canonical/lxd/issues/13191
=> Upload image to temporary dir and then move it

images/centos.yaml, images/fedora.yaml, images/openeuler.yaml, images/springdalelinux.yaml
Cherry picked from https://github.com/lxc/lxc-ci/pull/821
=> Fix missing whitespaces around dracut add_drivers+=

.github/workflows/image-ubuntu.yml
I've accidentally enabled scheduled Ubuntu build in #120
=> Disable scheduled build for Ubuntu images

bin/helpers, bin/test-image
Tests for CentOS images are occasionally failing, therefore give CentOS images an extra minute to boot.
=> Fix CentOS timeout on boot during test

bin/helpers, tests/cluster
From https://github.com/canonical/lxd-ci/pull/116
=> Cluster upgrade cert tests

.github/workflows/image-opensuse.yml, .github/workflows/image-ubuntu.yml
Disable images that are consistently failing until issues are resolved:
- `opensuse/15.5/cloud`
- `ubuntu/noble` (desktop)
=> Temporary disable failing images

.github/workflows/image-slackware.yml
Publish slackware images when event type is schedule.
Seems that I've missed that one. Others are uploading as expected.
=> Upload Slackware images when event_type is schedule

tests/interception
When the snap doesn't support shiftfs (anything after 5.20), the key is set but ignore so it didn't cause any problem.
Putting that version detection in place will hopefully let me remember to drop it once 5.0 goes EOL.
=> tests/interception: only try to enable shiftfs on 5.0/* snap

tests/storage-vm, tests/storage-volumes-vm
This now tests if custom volumes can be snapshotted, copied and transferred both locally and using a remote as well as between the same and different storage drivers.
Follow up on https://github.com/canonical/lxd-ci/pull/138.
=> Tests: Check custom storage volume snapshots

.github/workflows/image-alpine.yml
Build Alpine arm64 images if schedule is `0 0 * * 1` (Monday midnight) or if triggered manually.
=> Build arm64 images for Alpine

.github/actions/image-setup/action.yml
lxd-imagebuilder repository is now public so we can directly clone it instead of using deploy keys.
=> Clone lxd-imagebuilder using git

.github/actions/image-setup/action.yml
Missing `make` package..
If there will be more issues, I will disable other builds and ssh into the instance using tmux, as I have no other options to test this before opening a PR..
=> image-setup: Add missing make package

.github/actions/image-setup/action.yml, .github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml, images/mint.yaml
Add Linux Mint daily builds and remove no longer used deploy keys.
@tomponline Secret `LXD_IMAGEBUILDER_KEY` can be removed. I guess it was not, since builds did not complain.
=> Add Linux Mint

.github/workflows/image-mint.yml
Before that:
```
$ yamllint .github/workflows/image-mint.yml 
.github/workflows/image-mint.yml
1:1       warning  missing document start "---"  (document-start)
3:1       warning  truthy value should be one of [false, true]  (truthy)
52:81     warning  line too long (93 > 80 characters)  (line-length)
81:6      error    syntax error: expected <block end>, but found '<block sequence start>' (syntax)
86:81     warning  line too long (110 > 80 characters)  (line-length)
```
After that adding the missing space:
```
$ yamllint .github/workflows/image-mint.yml 
.github/workflows/image-mint.yml
1:1       warning  missing document start "---"  (document-start)
3:1       warning  truthy value should be one of [false, true]  (truthy)
52:81     warning  line too long (93 > 80 characters) …
```
=> github: fix image-mint.yml syntax

.github/workflows/image-funtoo.yml
Funtoo `1.4` is EOL. Use `next` release.
https://www.funtoo.org/Support_Matrix
Closes: https://github.com/canonical/lxd/issues/13352
=> github/workflows: Use Funtoo next release

.github/actions/image-setup/action.yml
Install lxd-imagebuilder from Snap. This should solve current issues with arm builds.
=> images: Install lxd-imagebuilder from Snap

.github/workflows/image-alpine.yml
Temporary disable arm64 VM builds.
Also do not build amd64 images when building arm64 images. This ensures we do not republish amd64 images when arm64 images built (especially now during testing), as it will make delta files from previous days useless.
=> images: Disable Alpine arm64 VMs

.github/workflows/image-almalinux.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml
Enable arm64 container image builds.
I've also disabled arm64 image builds for images that require cgroup v1.
=> images: Enable arm64 container builds

bin/build-distro
This way, I can use this invocation:
```
root@t1:~/lxd-ci# ./bin/build-distro "images/ubuntu.yaml" amd64 vm 1800 "${HOME}/build" -o image.architecture=amd64 -o image.release=noble -o image.variant=desktop -o source.url="http://archive.ubuntu.com/ubuntu"
```
Which previously failed due to the earlier `cd`:
```
root@t1:~/lxd-ci# ./bin/build-distro "images/ubuntu.yaml" amd64 vm 1800 "${HOME}/build" -o image.architecture=amd64 -o image.release=noble -o image.variant=desktop -o source.url="http://archive.ubuntu.com/ubuntu"
cp: cannot stat 'images/ubuntu.yaml': No such file or directory
```
=> bin/build-distro: make it easier to use relative path for YAML

.github/workflows/image-ubuntu.yml, images/ubuntu.yaml
Disable systemd-networkd on Ubuntu Noble desktop images which causes delays on boot.
I've left images for previous releases intact, but as @daniloegea suggested, should we disable systemd-networkd for all previous releases as well, if Ubuntu Desktop uses NetworkManager by default?
Closes https://github.com/canonical/lxd/issues/13387
=> images: Ubuntu Noble desktop

.github/workflows/image-debian.yml
The fastly CDN should provide close HTTPS endpoint wherever our GitHub Action runner VMs are located.
=> github: switch to HTTPS URL for debian and use fastly CDN

.github/actions/image-test/action.yml, bin/test-image, images/alpine.yaml, images/archlinux.yaml, images/gentoo.yaml, images/nixos.yaml
Fixes https://github.com/canonical/lxd/issues/13409
Also, fix/improve a few things along the way.
It's too bad that `bin/test-image` cannot consult the image requirements otherwise it would have been possible to look if the image being tested is not going to work with `secureboot`. For now I hardcoded the known incompatible distros but if @MusicDin you know better, please let me know!
=> Fix name of `secureboot` requirement

tests/container-copy
This is attempting to avoid having the guest's time being behind the host:
```
==> Add the target VM as a remote LXD
++ lxc exec target -- lxc config trust add --name host --quiet
+ token=eyJjbGllbnRfbmFtZSI6Imhvc3QiLCJmaW5nZXJwcmludCI6IjY0NjRkZGY3MWIyZTZlZjRhNDBlYTZmY2ZlNzY5Nzg2Zjk0NDc5OTIyYmM4ZWM1OWU0YmMzZmJjZjEzZTM3YTAiLCJhZGRyZXNzZXMiOlsiMTAuMTAyLjExLjEzNTo4NDQzIiwiW2ZkNDI6OTMxODo0YWQ0OmRiY2Q6MjE2OjNlZmY6ZmUxZDo5ZTkyXTo4NDQzIiwiMTAuMTA3LjI1MC4xOjg0NDMiLCJbZmQ0MjplZDc4OjcyYTI6OGRjMzo6MV06ODQ0MyJdLCJzZWNyZXQiOiI2ZTIzOTcxMmRjZGY0YzEzZmZmYWZhOWI5ZTkyNDdlNGZhZjE2MTQ2YzFjMmZhYTE2ZjIzZTllM2ZmNzZlN2NjIiwiZXhwaXJlc19hdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIn0=
+ lxc remote add target eyJjbGllbnRfbmFtZSI6Imhvc3QiLCJmaW5nZXJwcmludCI6IjY0NjRkZGY3MWIyZTZlZjRhNDBlYTZmY2ZlNzY5Nzg2Zjk0NDc5OTIyYmM4ZWM1OWU0YmM …
```
=> tests/container-copy: wait for host time to stabilize before creating VM

.github/workflows/image-debian.yml
We know Debian Sid doesn't work ATM but the server team is busy merging stuff from Debian into Ubuntu Oracular. Having the ability to launch Sid instances would help them.
I think we should be merging it now even if known broken because eventually it will start working on its own. Until it does, we'll also have traces of where it fails.
=> Revert "github/workflows: Disable Debian Sid"

.github/workflows/image-alpine.yml
https://alpinelinux.org/posts/Alpine-3.20.0-released.html
https://alpinelinux.org/releases/ shows 3.16 EOL on 2024-05-23
=> github: drop alpine 3.16 (EOL) and add 3.20

tests/storage-vm
Per Tom's request in https://github.com/canonical/lxd/pull/13470
EDIT: Not clear why tests are passing; they shouldn't. Will look at this more tomorrow.
=> tests/storage-vm: Check volume size rounding

.github/workflows/tests.yml, tests/tpm-vm
Adding tests for basic TPM usage on VMs, with included tests for handling TPMs with long names (see [#13320](https://github.com/canonical/lxd/pull/13320))
=> Add tests for TPM usage

.github/workflows/image-centos.yml, images/centos.yaml
CentOS 8 Stream has reached EOL.
https://endoflife.date/centos-stream
https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
=> Stop building CentOS 8 Stream (EOL)

.github/workflows/commits.yml, .github/workflows/tests.yml, tests/docker, tests/interception
Current issues with the PR:
* The workaround for needrestart should be reported on LP: https://bugs.launchpad.net/ubuntu/+source/needrestart/+bug/2067800
* `tests/cluster` fails on 24.04 due to the kernel temporarily missing `fan` support (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2064508)
* `tests/docker` required a local workaround Apparmor rule to allow `pivot_root` (https://github.com/canonical/lxd/issues/13389)
* `tests/interception` fail likely due to having `.ko.zst` compressed (working on a potential fix)
* `tests/storage-vm zfs` fails due to `zfs` missing the rounding fix by @MggMuggins
* `tests/tpm` is failing due to overly long path (patch to be merged/backported, @hamistao is aware of it)
=> github: switch to using 24.04 on CI runners

images/alpine.yaml
Build Alpine edge based on `3.20` instead of `3.12` development branch.
Fixes https://github.com/canonical/lxd/issues/13414
=> alpine: Build edge based on latest release

.github/workflows/image-fedora.yml
https://discussion.fedoraproject.org/t/f38-is-end-of-life/117727
=> github: Fedora 38 reached EOL on 2024-05-21

tests/storage-disks-vm
Devices with long names can cause some problems due to socket paths or device tags that include those names being too long, resulting in errors from QEMU. See [#13320](https://github.com/canonical/lxd/pull/13320) and [#15516](https://github.com/canonical/lxd/pull/13516).
=> Add tests for handling disk devices with long names

tests/cpu-vm
It was discovered, that current check, while being correct in theory works really bad in practice. Because QEMU sometimes spawns additional temporary threads from an actual vCPU threads which leads to the situation when we have more threads with pinning applied than vCPU number. Let's relax our check a bit and check for "greater than" and not for the equality.
https://warthogs.atlassian.net/browse/LXD-1200
=> cpu-vm: relax cpu pinning check a bit

tests/cluster
This replaces `ping` that's not on -minimal images by `bash` TCP probing of SSH.
This was tested on a 24.04 host with `6.8.0-38-generic` kernel (the one re-introducing FAN support on Noble).
=> tests/cluster: switch to -minimal image

tests/tpm-vm
The test was missing FAIL=0 so could have never possibly been run successfully.
=> test/tpm-vm: Fix TPM test so that it doesn't always fail

tests/network-ovn
I've added some basic tests for automatic allocation of IP addresses for OVN network forwards and load balancers.
I've found it difficult to make these tests more extensive because the allocated IPs are random but the tests rely on hardcoded IPs. To avoid collisions we need to keep track of whether or not forwards/load balancers have been created with allocated IPs (by the API extension) and delete them before creating new forwards/load balancers with a fixed IP on any network using the same uplink.
I think it's fine for now to just ensure they can be created/deleted and that new ones can't be created with the same IP. There is no difference in code path/functionality between allocated/fixed IP after initial creation.
=> tests: Add basic IP allocation tests

README.md, bin/helpers
Adds a new environment variable `ENABLE_SIDELOADING` which stops the LXD daemon, then starts it again when the user presses enter. This allows time for loading a custom build.
I found this useful in my local testing.
=> bin: Allow sideloading of lxd binaries

bin/test-image
Commit in #185 broke many image tests (especially older releases) by using `isSystemdClean` function. Function also uses `systemctl --wait` flag which is not supported on older releases.
=> revert: bin/test-image: use isSystemdClean() helper function

tests/storage-vm
The default size of the config drive for PowerFlex backed VMs is 8GiB. This requires setting a higher memory value for the VM to trigger the error if `size.state` is too small.
=> Tests: Add exception for PowerFlex stateful migration checks

tests/storage-vm
This is using the migration send/receive functions of the respective storage driver.
Tests the fix from https://github.com/canonical/lxd/pull/13612.
=> tests/storage-vm: Add VM move test between storage pools

tests/storage-disks-vm
Check that a directory share passed to a VM at boot time can be hot unplugged.
=> test/storage-disks-vm: Improvements to the directory passthrough tests

.github/workflows/tests.yml, tests/storage-buckets
https://dl.min.io/server/minio/release/linux-amd64/minio works but not https://dl.min.io/server/minio/release/linux-x86_64/minio
This test is still inactive (in the excluded section of the testing matrix) because it's waiting on the integration of microceph.
=> tests/storage-buckets: enable test except for ceph pools

bin/test-image, images/openeuler.yaml
openEuler VMs do not start if secureboot is enabled.
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/9586102046/job/26433364126
Fixes https://github.com/canonical/lxd/issues/13636
=> Disable secureboot for openeuler

tests/storage-disks-vm
Also depends on https://github.com/canonical/lxd/pull/13674 in order to resolve an internal race between qemu/guest OS and lxd-agent.
=> test/storage-disks-vm: Wait for agent to mount path inside guest

README.md, bin/helpers
This adds a new variable `POWERFLEX_MODE` that allows running the PowerFlex storage tests either in `nvme` or `sdc` mode.
=> Tests: Add support for the PowerFlex SDC operation mode

bin/test-image
Revert https://github.com/canonical/lxd-ci/pull/205
We cannot extract `requirements` from manually built images, as LXD retrieves them from the image server - they are not part of the image metadata.
This should fix issues with VM tests on Alpine, Arch, ...
Example passing build for Alpine: https://github.com/MusicDin/lxd-ci/actions/runs/9712230286
=> bin/test-image: Disable secureboot for specific images

.github/actions/image-setup/action.yml
Ensure package `bzip2` is installed. It is installed by default on amd64 runners, but is missing on arm64 runners which causes an issue when decompressing busybox image.
```
Error: Error while downloading source: Failed to unpack "busybox-1.36.1.tar.bz2": Unpack failed: Failed to run: tar --restrict --force-local -C /home/runner/build/cache/src --numeric-owner --xattrs-include=* -jxf -: exit status 2 (tar (grandchild): bzip2: Cannot exec: No such file or directory
```
=> image-setup: Ensure bzip2 package is installed

.github/workflows/image-openeuler.yml
Adds 24.03 LTS release and uses US mirror. The mirror is disabled for `22.03` because files are currently missing on the mirror.
Here is the passing build (all except 22.03 which is still being downloaded while other releases are already built and tested): https://github.com/MusicDin/lxd-ci/actions/runs/9746516110/job/26897050776
=> openeuler: Add 24.03 LTS release and use US mirror

.github/actions/image-setup/action.yml
Follow up on: #220
Adding package `build-essential` to the list of required packages.
Current error is [`gcc: not found`](https://github.com/canonical/lxd-ci/actions/runs/9746540143/job/26897139278#step:4:129) on arm64 runner.
=> image-setup: Ensure package build-essential is installed

.github/workflows/image-devuan.yml
Devuan 3/Beowulf is based on Debian 10/Buster which went EOL on 2024-06-30 (#223)
=> github: Drop Devuan 3/Beowulf images (EOL)

.github/workflows/image-nixos.yml, bin/test-image
https://discourse.nixos.org/t/nixos-24-05-released/46279:
> The 23.11 “Tapir” release is now officially deprecated, and will reach its end-of-life and stop receiving security updates after 2024-06-30.
=> NixOS 23.11 (EOL: 2024-06-30)

.github/workflows/image-openeuler.yml
https://www.openeuler.org/en/other/lifecycle/ says:
> LTS version: released every two years and provides community support for four years. openEuler 20.03 LTS, the first LTS version, was released in March 2020.
This means it went EOL in March 2024 which is also confirmed by the graph on the same page.
Also, 23.03 is not a LTS release so:
> Innovation version: released every six months and provides community support for six months.
So it went EOL at the end of 2023.
=> github: Drop OpenEuler 20.03 LTS and 23.03 images (EOL 2024-03)

tests/storage-disks-vm, tests/storage-vm, tests/storage-volumes-vm
This adds tests for checking if `/dev/disk/by-id` links are being properly set up for different kinds of block devices. Also moves non pool specific tests away from `storage-vm`.
This is needed for [#13672](https://github.com/canonical/lxd/pull/13672) and [#13671](https://github.com/canonical/lxd/pull/13671).
=> Add `/dev/disk/by-id` link tests

bin/README.md, bin/testflinger-run, bin/tf-reserve
* Reserving an NVIDIA ORIN board can be done with the following comments at the beginning of a test script:
```bash
```
* `tf-reserve` has also been updated to take a `media` parameter. Example:
```bash
$ export LP_USER=gabrielmougard
$ tf-reserve  nvidia-jetson-agx-orin https://cdimage.ubuntu.com/nvidia-tegra/ubuntu-server/jammy/daily-preinstalled/current/jammy-preinstalled-server-arm64+tegra-igx.img.xz usb
```
* How to flash an Nvidia AGX board: https://docs.google.com/document/d/1YhwbyWNGz4K8k8zsKhMBqbII5NkuD70cxCfOs5aPOl0/edit
* Target ORIN board on TF: https://certification.canonical.com/hardware/202306-31646/
=> bin: Update `tf-reserve` and `testflinger-run` for Nvidia AGX board

tests/tpm-vm
This even longer name tests for problems with device ID trmming on QEMU and tests using `/` in TPM names. See [#13671](https://github.com/canonical/lxd/pull/13671).
=> Update long device name on TPM tests

.github/workflows/tests.yml, bin/helpers, tests/cluster, tests/container, tests/cpu-vm, tests/interception, tests/network-bridge-firewall, tests/network-routed, tests/vm-nesting
This adds 15 tests to the existing test matrix. This put the current total at 105 jobs taking ~15 hours of CI runtime.
=> github: extent test matrix to 4.0/edge and 20.04

bin/test-image
```
root@cloud:~/lxd-ci# ./bin/test-image container debian bookworm cloud ~/build/
==> Fetching the image
Image imported with fingerprint: 102e1df1d4f872c0952870649de4f22233770bb4b4fe810fbf43993ccc34c4c4
==> Creating the instances
Creating container-debian-cloud-priv
Creating container-debian-cloud-unpriv    
==> Starting the instances                
==> Waiting for instances to start
+-------------------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
|             NAME              |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+-------------------------------+---------+----------------------+-----------------------------------------------+-----------+------- …
```
=> bin/test-image: do a post cloud-init reboot test for cloud variants

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml
Prevents running scheduled image builds on repository forks.
There are some alternative solutions, but IMO limiting scheduled image builds to `canonical/lxd-ci` repository is most suitable:
- Disable actions on fork (This prevents running a workflow manually on fork)
- Disable specific workflows (This prevents running a workflow manually on fork)
- Remove main branch on the fork or apply those changes on the main branch (This needs to be done on each fork - works for me, but thought this change would be nice for all forks)
=> images: Run scheduled image builds only on `canonical/lxd-ci` repo

tests/storage-disks-vm
#231 is a prerequisite.
This removes the last `sd*` reference and adds tests for `sd*` name assignments with coldplugged disks.
=> Handle `sd*` disk names

bin/test-image
I've tried reproducing the issue with cloud-init check failing after reboot locally, but without success. However, I'm able to reproduce the issue consistently on GH runners.
I'm suspecting that cloud-init is invoked before instance is fully ready.
Adding a 10 second delay after instance is *fully* ready fixes the issue. It is not the most convenient one, but is the similar approach we use when we initially create instances.
https://github.com/canonical/lxd-ci/blob/b54cb611530c537c00035684326337af53568688/bin/test-image#L167-L168
Here are some builds on fork using this *fix*:
- AlmaLinux: https://github.com/MusicDin/lxd-ci/actions/runs/9843294370
- Oracle linux: https://github.com/MusicDin/lxd-ci/actions/runs/9843273759
- Alpine linux (3 attempts - all successful): …
=> images: Fix cloud-init check after reboot

.github/actions/image-upload/action.yml
We had a few workflows fail when trying to upload their images to the backing server:
```
$ sftp ...
Host key verification failed.
Connection closed.
```
The unexpected host key was also seen on job retries but only for a few runners. While this looked very suspicious, I think the explation is fairly simple.
When we setup the images server, we removed all host keys but the Ed25519 one. This is then the key whose fingerprint is hardcoded in the runners building the images (in their `~/.ssh/known_hosts`).
However, on July 2nd 2024, I (`10.131.10.107` is my VPN IP) pulled the updates on the images server due to a security fix landing for openssh:
```
ubuntu@prod-lxd-images:~$ last -ai | head -n 3
ubuntu   pts/0        Wed Jul 10 20:59   still logged in    10.131.10.107
ubuntu   pts/0 …
```
=> github: force ed25519 host key algo in image-upload

tests/storage-disks-vm
Hotplugging directories has been allowed since canonical/lxd@fff4b19. The test was passing anyway because the command syntax was incorrect, missing the mount path argument.
=> Update dir hotplug tests

tests/storage-volumes-vm
Adds tests for custom block volume sharing on VMs and `security.shared` usage. See canonical/lxd#13183.
=> tests/storage-volumes-vm: Add tests for custom block volume sharing

.github/workflows/tests.yml
So as not to cancel scheduled tasks when initiating manual runs.
=> github: Separate workflow concurrency groups based on event name

tests/container-copy, tests/storage-vm, tests/storage-volumes-vm
This is just the first cut at storage operation integrity checks. I intend to implement your `lxc file mount` suggestion for containers in a future PR but if you prefer it to be bundled here, that's OK too.
=> Storage operation integrity checks

.github/workflows/tests.yml, tests/conversion, tests/main-openstack, tests/main-testflinger
Adds tests for image conversion using lxd-migrate.
Tests:
- Container migration over conversion API.
- VM conversion from QCow2, and VMDK formats.
- Ensure `lxd-migrate` falls back to migration if server does not support conversion API extension (this should occur both for VMs and containers).
=> Add test for image conversion using lxd-migrate

.github/workflows/image-openeuler.yml
The mirror has been updated to include 22.03 release. Therefore, exception in action step is no longer required.
Passing build (on fork): https://github.com/MusicDin/lxd-ci/actions/runs/10140831559
=> images: Remove openEuler mirror exception for release 22.03

.github/workflows/tests.yml, tests/conversion
Ensures that importing raw image and image conversion are made on all storage drivers (dir, zfs, lvm, btrfs).
Raw image import was missing `dir`, `lvm`, and `btrfs`.
Conversion was missing `lvm`.
=> tests/conversion: Test all storage pool drivers

tests/vm-migration
This PR gets the VM live migration test passing by waiting for the instance to boot before performing the migration.
=> VM live migration test fix

bin/helpers, tests/devlxd-container
The `devlxd-container` tests are timing out when waiting for snapd to be seeded inside the container that will run a nested LXD.
This PR calls `waitInstanceBooted` after the container starts, then waits indefinitely for snap to be seeded. This approach is that same as in the `cluster` test.
=> Fix intermittent failure on snapd seed

images/almalinux.yaml, images/alpine.yaml, images/archlinux.yaml, images/centos.yaml, images/debian.yaml, images/fedora.yaml, images/gentoo.yaml, images/openeuler.yaml, images/opensuse.yaml, images/rockylinux.yaml, images/springdalelinux.yaml, images/ubuntu.yaml
Cherry-picked from https://github.com/lxc/lxc-ci/pull/822
Passing workflows:
- Alpine: https://github.com/MusicDin/lxd-ci/actions/runs/10269160208
- CentOS: https://github.com/MusicDin/lxd-ci/actions/runs/10269156356
=> images: Fixed hardcoded root partition device name sda2

tests/devlxd-container
Stop testing for extensions supported by the oldest LXD version still supported.
=> tests/devlxd-container: devlxd_images and event_lifecycle are supported by LXD 4.0+

.github/workflows/tests.yml, bin/helpers, tests/snapd
This PR adds a quick check to ensure that preseeds set via snap are handled, and makes updates to `tests/snapd` to remove redundant testing. 
`tests/snapd` now runs in the pipeline.
=> tests/snapd: Add quick check for snap preseed handling

bin/helpers, tests/devlxd-vm
Amends `devlxd-vm` to test for image export over devlxd. To test this locally, I added functionality to the tests to allow sideloading the lxd-agent.
=> Test devlxd image export for virtual machines

tests/storage-disks-vm
This test has shown to be flaky because the device is not effectively added before the next command executes (See https://github.com/canonical/lxd-ci/actions/runs/10297255515/job/28500067002#step:8:637).
So a short sleep makes this test more consistent, as it is already done in other places in the tests where hotplugging devices is performed.
=> Sleep after hotplugging block dev

.github/workflows/image-alt.yml
https://packages.altlinux.org/en/p9/about/:
> Support end date: Dec. 31, 2023
=> github: ALT p9 is EOL

.github/workflows/image-voidlinux.yml
There doesn't seem to be any 23.11 release: https://mirrors.servercentral.com/voidlinux/live/
It has 2 variants (`default` (glibc) and `musl`) but we only provide the `default` one.
=> github: Void Linux only has a current release

.github/workflows/tests.yml, tests/storage-vm
Frees up an additional ~11G on the rootfs.
This reduce the likelihood of running out of space during the storage tests.
=> Out of space

tests/devlxd-container
The `waitInstanceBooted` function was failing because systemctl inside the container was sometimes reporting a degraded state after the force stop. This doesn't matter for the purpose of this test. Now we just wait for the instance to show some processes, then ensure that snapd is running before we call `snap wait system seed.loaded`.
=> tests: Fix devlxd-container tests.

tests/container, tests/container-copy, tests/storage-vm
The whole point of using token is to avoid blindly trusting a random server certificate. IMHO, LXD should refuse this combo (https://github.com/canonical/lxd/issues/13973).
=> Don't use `--accept-certificate` when consuming token

tests/storage-vm
=> tests/storage-vm: don't wait before comparing VM gen IDs

images/centos.yaml
Removes xattr `security.selinux` on container CentOS 9-Stream images.
I've tried suggestion from @simondeziel with `+` at the end of the `find` command to process files in bulk, but it always resulted in an error - it may be that I've missed something. Feel free to improve.
Passing build on fork: https://github.com/MusicDin/lxd-ci/actions/runs/10745316648/job/29804098029
=> images: Remove security.selinux extended attributes on CentOS images

tests/qemu-external-vm
Testing only on `latest/edge` means that we'll need to revisit the condition when the next LTS occurs. Let's do it now as we know what to skip already.
=> tests/qemu-external-vm: rework version based skipping

tests/devlxd-container, tests/devlxd-vm
This is needed because [#14056](https://github.com/canonical/lxd/pull/14056) changed how we identify a request as coming from the /dev/lxd socket. If version checking for 5.21 and after is needed here please let me know. Not sure how/if the metrics will be backported.
=> tests: Update devlxd request source identification

.github/workflows/tests.yml, tests/container, tests/vm
As was discussed with @mihalicyn If containers are stopped gracefully, the exit code can be 129(SIGHUP) or 143(SIGTERM) depending on the signal used, both results have been seen and make sense. If forcefully stopping a container the exit code is always 137 (SIGKILL). For VMs, the exit code was standardized as 129 for all cases by [#13875](https://github.com/canonical/lxd/pull/13875) (not merged yet).
In its current state, this PR only adds tests for forcefully stopping containers and VMs.
=> Tests for disconnections during `lxc exec`

tests/conversion
This is a temporary fix for conversion tests, and to allow me to test `lxd-migrate` in non-interactive mode (https://github.com/canonical/lxd-ci/pull/283). It also cleans up the instance and pool naming to reduce duplication.
Passing conversion tests on fork: https://github.com/MusicDin/lxd-ci/actions/runs/10937871555
=> tests: Disable SELinux before exporting CentOS image

tests/conversion
Add tests for non-interactive usage of `lxd-migrate` (using flags).
=> Add tests for non-interactive lxd-migrate commands

tests/conversion
This uses `--quiet` to workaround https://github.com/canonical/lxd/pull/14129
that may not be backported.
=> tests/conversion: conserve CPU/disk by exporting to stdout

tests/storage-vm
This part of the `storage-vm lvm` test went from ~3m30s down to ~25s.
=> tests/storage-vm: faster export check for config.mount exclusion

tests/container, tests/storage-vm
- Launching an aliased container image shouldn't launch with the `--vm` flag; and
- VM's should be launched with `--vm` flag.
=> tests/container: Add test to ensure launching an aliased container image won't launch with vm flag

tests/conversion
Rather than assume it is there or not, let's only disable it if the config file is present. This should keep it working even if SElinux is reintroduced in the image.
=> tests/conversion: SELinux is no longer in `images:centos/9-Stream`

images/kali.yaml
When cloud-init is installed, the `systemctl enable cloud-init` fails. The service is now called `cloud-init-main`.
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/11165385223
=> images/kali: Fix enabling cloud-init service

bin/helpers, tests/cgroup
When cgroup2 is used there is a difference between root of cgroupfs tree and sub-cgroups. When we do a cgroup feature checking we should check for `memory.swap.max` file existence in a `/sys/fs/cgroup/system.slice/memory.swap.max` instead of `/sys/fs/cgroup/memory.swap.max`.
See also:
https://github.com/lxc/lxcfs/commit/f496e62cdbeb01215af34fed266fc5a98d25feeb
=> Fix tests/cgroup on cgroup2

.github/workflows/tests.yml, bin/local-run, tests/cgroup, tests/container-copy, tests/vm-migration, tests/vm-nesting
This includes a few small unrelated tweaks.
=> Use `security.devlxd.images` with VMs where applicable

news/weekly-changes.sh
Re-adds TF provider section, which seems to be accidentally removed in https://github.com/canonical/lxd-ci/pull/306
=> news: Add LXD Terraform provider section

.github/workflows/tests.yml
This modules is not normally loaded on stock Ubuntu installs but it is on GHA runners.
Fixes https://github.com/canonical/lxd/issues/13069
=> github: unload br_netfilter module

tests/container, tests/vm
When cleanly stopping a VM in the middle of lxc exec, two things can happen:
1- The agent is stopped first, in which case the connection with LXD is severed and we are supposed to get a 129 exit code on the client;
2- The spawned process is stopped first and the agent is able to respond before it also stops. In this case, we are supposed to get the exit code based on the signal that was used to stop the process;
This adds tests for these two scenarios separately.
=> Improve testing a stop in the middle of lxc exec

tests/network-ovn
This PR adds testing for when an OVN uplink network is attached to a VLAN.
=> Add testing for OVN uplink attached to VLAN

.github/workflows/tests.yml
Out of the blue, `tests/vm-nesting` became our biggest [CI consumer](https://github.com/canonical/lxd-ci/actions/metrics/usage?tab=jobs). This was because at some point, that test simply stopped making progress so instead of taking < 15 minutes it would hang for 6 hours and eventually be [cancelled due to timeout](https://github.com/canonical/lxd-ci/actions/runs/11282145005/job/31379018916#step:9:3258).
Our current slowest test is `tests/storage-lvm` when ran on `24.04` and even this very slow combo finishes inside ~45 minutes. Allowing up to twice as long before timing out should provide enough headroom while also limiting the CI waste if a similar hang ever appears again.
=> github: abort system-tests after 60 minutes

bin/test-image
This is mainly to enable the cloud-init testing of desktop images for which we only build a single variant called `desktop`.
=> bin/test-image: check if cloud-init cmd is available on non-cloud variants

tests/network-ovn
This PR adds checks to ensure that network forwards can be created using an OVN network's own volatile IP.
Addresses https://github.com/canonical/lxd-ci/pull/333#discussion_r1823123705.
=> tests: Add testing for successful forward creation using an OVN network's own volatile IP

tests/network-ovn
Depending on https://github.com/canonical/lxd/pull/14210
=> Test OVN external addresses show on `lxc network list-allocations`

images/alt.yaml
Disable `update_hostname` module in cloud-init to prevent errors on reboot.
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/11682041046
=> images/alt: Disable `update_hostname` cloud-init module

bin/helpers
@MusicDin as you asked the other day, this tweaks the `cleanup` function to not spit a wall of text on failure unless ran on GHA runners.
=> Allow sideloading `lxc`

.github/workflows/image-alt.yml, .github/workflows/image-devuan.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-oracle.yml
With @simondeziel we have checked the metrics for images, and this PR drops builds for unused images, especially focusing on distributions that are very *heavy* to build, such as Funtoo, and openEuler.
This removes builds for:
- Devuano (arm64 only)
- Gentoo (arm64 only)
- Funtoo (arm64 only)
- openEuler 22.03 (all)
- openEuler 24.03 (arm64 only)
- Oracle 8 (arm64 only)
- ALT p10 (all)
=> Cleanup unused images

news/weekly-changes.sh
This was flagged on the last weekly news review, so it should be better to update the script and not worry about this anymore.
=> news: Correct bug fix section title

images/almalinux.yaml
The uwaterloo.ca mirror lost the `/almalinux/9/isos/x86_64/` dir it seems. Their primary download location has it still.
=> images/almalinux: update download source

.github/workflows/tests.yml
Fixes bug I introduced when trying to avoid text walls in `cleanup()` on failure. I didn't think of `sudo` stripping the environment.
=> github: pass GITHUB_ACTIONS to test scripts

.github/workflows/image-openwrt.yml, images/openwrt.yaml
Recently, openWRT changed their package manager from "opkg" to "apk" (Alpine Linux package manager).
Post from openWRT forum: https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/11940145394/job/33282183927
=> images/openwrt: Use apk as package manager

tests/cluster
This allows us to test for container stop support after upgrading between core snap versions.
=> tests/cluster: Test for container stop after snap channel upgrade

images/alt.yaml
The issue with ALT cloud-init was fixed in the downstream as reported back by @holmanb in https://github.com/canonical/lxd-ci/pull/344#issuecomment-2545825708 (See [Bug in downstream altlinux](https://bugzilla.altlinux.org/52029)). This PR removes the previously introduced workaround.
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/12355203098/job/34478274649
=> images/alt: Remove cloud-init workaround

bin/helpers, tests/vm-migration
This is the first step toward not relying on GH actions to setup MicroCeph's snap. It replaces the ad-hoc manual setup by a set of 2 helper functions.
For now, it's only used to replace the `ceph` VM from the `tests/vm-migration` by a `microceph` snap deployed in the GHA runner VM. For now it doesn't use the ephemeral disk but a loop-backed file.
=> Turn microceph setup into a reusable helper

.github/workflows/image-fedora.yml
This reverts commit 8d57a1c5a243dd1f09e7125a4a3af961f1d14343 due to https://github.com/canonical/lxd/issues/14711
=> Revert "github: add Fedora 41"

.github/workflows/image-oracle.yml, images/oracle.yaml
https://www.oracle.com/a/ocom/docs/elsp-lifetime-069338.pdf:
> Premier Support Ends on Dec 2024 for Oracle 7
https://www.oracle.com/a/ocom/docs/linux/oracle-linux-extended-support-ds.pdf:
> Oracle Linux Basic and Premier Support are available for 10 years after the initial release of every version of Oracle
Linux, Red Hat Enterprise Linux (RHEL), and CentOS Linux1. This is the production support period. After this period,
Oracle Linux Extended Support is available for a number of years, depending upon the release and version2. Oracle
Linux Extended Support requires an underlying Oracle Linux Premier Support contract.
=> Oracle7 no longer supported without support contract ($)

tests/network-ovn
This should work in `latest/edge` now that https://github.com/canonical/lxd/pull/14327 was merged.
=> Revert "tests/network-ovn: ignore empty ACL logs if not using deb"

.github/actions/image-upload/action.yml
The `env` key cannot be located under `runs` in composite actions.
=> actions/image-upload: Fix env field location

.github/actions/image-upload/action.yml
Set `SSH_AUTH_SOCK` for the upload step to make SSH agent accessible.
=> actions/image-upload: Ensure SSH agent is accessible during upload

tests/storage-volumes-vm
This should have a check for all corner cases around VM root volume attachments (coverage for https://github.com/canonical/lxd/pull/14532):
- security.protection.start allows one other VM to attach the machine's root disk, and can only be removed if the disk is not attached
- security.shared allows unchecked attachments of root disks
- VM attachments are correctly reported in used_by
- hotplug of VM root attachments works (as this is the method reccomended by the docs to avoid UUID/LABEL conflicts)
I ran into an interesting behavior of udev in Noble VMs while testing that slowed this down a bit. In order for udev to create a symlink for `SCSI_IDENT_SERIAL` (`/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_lxd_virtual--machine-vm5`), I had to hotplug the device in an `ubuntu:24.04` VM. Starting …
=> tests/storage-volumes-vm: Root volume disk device attachments

tests/gpu-container
Validation fixes from https://github.com/canonical/lxd/pull/14535 were not reflected in this test.
=> tests/gpu-container: Fix CDI tests with respect to dGPU passthrough and updated LXD validation

.github/workflows/tests.yml
The problem with the `include` set is that if one asks to run all tests for say `5.21/edge` on `22.04`, the `include` set will also be added to the mix which is not desired.
=> github: change how qemu-external-vm test is added to the test matrix

tests/network-ovn
This originally contained tests for https://github.com/canonical/lxd/pull/14631, but we moved the tests to the lxd ovn test suite and this was repurposed to just fix a wrong string that refers to a bridge network as physical.
=> Fix echo string in ovn tests

README.md, tests/storage-vm
Observed whilst running the tests for https://github.com/canonical/lxd/pull/14865.
Also added a note to run more robust PowerFlex tests that cope with zero-padding disabled.
=> Fix check for PowerFlex volume size

tests/storage-volumes-vm
This is what we do for the other tests that check symlinks for hotplugged devices.
=> storage-volumes-vm: Give udev time to create symlink

bin/helpers
The `apt-get` way worked but caused every pending update to be applied, not just snapd's because `apt-get upgrade` ignore package selection:
```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
dotnet-runtime-6.0 linux-azure linux-cloud-tools-azure linux-headers-azure
linux-image-azure linux-tools-azure sosreport
The following packages will be upgraded:
apache2 apache2-bin apache2-data apache2-utils aspnetcore-runtime-6.0
aspnetcore-targeting-pack-6.0 bind9-dnsutils bind9-host bind9-libs
cloud-init distro-info-data dmidecode dotnet-apphost-pack-6.0
dotnet-hostfxr-6.0 dotnet-targeting-pack-6.0 firefox
gir1.2-packagekitglib-1.0 libarchive13 libcurl3-gnutls …
```
=> bin/helpers: refresh snapd only after (old) snapd is seeded

tests/devlxd-container, tests/devlxd-vm
This adapts the CI to the changes introduced on https://github.com/canonical/lxd/pull/14852.
=> tests: Address `cloud-init` misconceptions

bin/helpers
Before, doing `snap install lxd` would pull LXD `5.21/stable` which is ATM based on `core22` but chances are that the custom LXD snap provided is a modern one based on `core24`. As such, you end up pulling `core22` just for getting your custom snap installable.
Instead, pull the official LXD snap from the requested channel which still works to give us the assert required to then be able to install custom LXD snap. This way, a virgin VM won't need to uselessly download `core22`.
=> bin/helpers: use proper channel when installing LXD from custom snap

tests/network
Tests related to https://github.com/canonical/lxd/pull/14905.
This PR add tests for physical NICs, confirming that `agent.nic_config` works as expected by checking the MTU and MAC address of a parent NIC added to a virtual machine.
=> tests/network: Add tests for `agent.nic_config` on VMs with physical NIC

.github/workflows/image-openwrt.yml
https://openwrt.org/releases/24.10/notes-24.10.0:
> OpenWrt 24.10.0 - First Stable Release - 6. February 2025
=> OpenWrt 24.10

.github/workflows/image-fedora.yml, images/fedora.yaml
Adds Fedora 41 release.
Requires:
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/12930858195
=> images/fedora: Add Fedora 41

.github/workflows/image-openwrt.yml
GitHub cuts `0` at the end resolving `24.10` into `24.1`.
This can be observed in this action run: https://github.com/canonical/lxd-ci/actions/runs/13203486797
Here is the passing build with quotes: https://github.com/MusicDin/lxd-ci/actions/runs/13204108061/job/36863042112
=> openwrt: Quote release ending with 0

tests/storage-disks-vm
Tests for https://github.com/canonical/lxd/pull/14898. I am assuming it will be backported into 5.21. If not, let me know and I shall update the tests accordingly.
=> tests: Test mount options for hotplugged dir share device

tests/storage-volumes-vm
Tests for https://github.com/canonical/lxd/pull/14929
I have verified that these fail before applying those changes.
=> tests/storage-volumes-vm: Test VM disk device unmount

tests/storage-vm
After landing https://github.com/canonical/lxd/pull/14993 the `storage-vm` test should only set the `storage.images_volume` config key for supported storage drivers.
Ceph RBD is not supported because it's volumes don't allow concurrent read/writes from multiple hosts.
=> Tests: Don't set storage.images_volume for Ceph RBD

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-fedora.yml, .github/workflows/image-kali.yml, .github/workflows/image-nixos.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-voidlinux.yml
Use public arm runners for building images.
Tested with few distros (CentOS, OpenSUSE, Alpine, Busybox), and works just fine.
Also drops AmazonLinux 2 which uses cgroup v1.
=> workflows/images: Use public arm runners

.github/workflows/tests.yml
Those runners are going away, starting on March 4, 2025 and the final cut will be on April 1st.
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
=> github: stop testing on ubuntu-20.04 runners

tests/storage-volumes-vm
Snapshot attachment tests for https://github.com/canonical/lxd/pull/14930
`latest/edge` will fail until that PR is merged.
I'm still looking at a `lxc storage volume detach` bug with LVM instance snapshots, but it only affects detach when the instance's root volume is also mounted. I will put up a PR/modify this one once I've tracked it down.
=> tests/storage-volumes-vm: VM snapshot attachment

tests/storage-volumes-vm
Double check that `readonly` works for block volumes (tests the change made in https://github.com/canonical/lxd/pull/15112)
=> tests/storage-volumes-vm: Readonly block volumes

tests/container
It is an attempt to fix failures like this:
```
+ echo '==> nested container (22.04)'
+ lxc launch ubuntu-minimal-daily:22.04 n1 -c security.nesting=true -c security.devlxd.images=true ==> nested container (22.04)
Launching n1
Retrieving image: Unpacking image: 100% (1.25GB/s)
Retrieving image: Unpacking image: 100% (1.25GB/s)
+ isSystemdClean n1
+ lxc exec n1 -- snap install lxd --channel=latest/edge error: cannot install "lxd": Post "https://api.snapcraft.io/v2/snaps/refresh":
context canceled
+ cleanup
```
=> tests/container: wait for snapd init before installing LXD snap

news/weekly-changes.sh
Adds empty sections for LXD UI and images in news template. It also removes the Ubuntu section from the template - so far I have never added anything to that section, so let me know if we still need it.
=> news: Add image and LXD UI sections

images/voidlinux.yaml
Fix the VoidLinux shutdown by creating a service that ensures `/etc/runit/stopit` exists with permissiong `100` on each boot.
Passing build: https://github.com/MusicDin/lxd-ci/actions/runs/14172602615
=> images/voidlinux: Fix container shutdown

.github/workflows/testflinger/uc-nvidia-job.yml
Make tests back to working condition.
It looks like there is some regression and 10_nvidia_wayland.json is not distributed anymore in nvidia-user component. I've reported this, but let's comment this test out temporary.
=> github/testflinger: fix NVIDIA Ubuntu Core tests

.github/workflows/testflinger/uc-nvidia-job.yml
Print contents of mesa-2404 snap.
Add a proper retries on modprobe (it is racy sometimes).
Resurrect a check for 10_nvidia_wayland.json as it's gonna be fixed soon (see https://github.com/canonical/lxd/pull/15301).
=> github/testflinger: improve NVIDIA Ubuntu Core tests

tests/cloud-init
Tests related to https://github.com/canonical/lxd/pull/15207
=> tests/cloud-init: Test support for `none` value for SSH key

.github/workflows/tests.yml, tests/storage-metadata
Should be landed together with https://github.com/canonical/lxd/pull/15129.
The new tests `storage-metadata` performs instance and custom storage volume exports/imports as well as migrations between older and newer versions of LXD.
=> tests: Add `storage-metadata` for checking the improved format

tests/storage-volumes-vm
Ensure that unmounting an LVM storage volume does not fail when one of its snapshots is in use.
This corresponds with https://github.com/canonical/lxd/pull/15162
=> tests/storage-volumes-vm: LVM (de)activation order

tests/cloud-init
This prevents failures such as https://github.com/canonical/lxd-ci/actions/runs/14237699920/job/39900238626 and includes other small fixes and improvements.
=> tests: Add jinja template tag on user data

tests/network-ovn
This should be merged together with https://github.com/canonical/lxd/pull/15305. This PR prevents removal of ipv4/ipv6 routes on the uplink if there are existing network forwards that rely on these routes.
The updated test does not remove routes required for already existing network forwards.
=> tests: Fix ovn_forward_tests in network-ovn

.github/workflows/tests.yml, tests/storage-metadata
Second try after https://github.com/canonical/lxd-ci/pull/428 got merged too early.
Should be landed together with https://github.com/canonical/lxd/pull/15129.
The new tests storage-metadata performs instance and custom storage volume exports/imports as well as migrations between older and newer versions of LXD.
=> tests: Add `storage-metadata` suite for checking the improved format

tests/cluster
The existing `tests/cluster` script didn't catch https://github.com/canonical/lxd/issues/15212 because upgrading LXD to the broken revision didn't touch the already created `lxdfan0` network device and the inner instances were not checked for connectivity after the upgrade anyway. https://github.com/canonical/lxd-ci/actions/runs/13917046846/job/38941869251 was one of the last test runs with the broken LXD revision.
Reboot the whole cluster after it's been upgraded has shown to catch the problem after I manually side-loaded a broken LXD (main with https://github.com/canonical/lxd/pull/15213/commits/197a0238f7f7d80c123f6e0c1716f4efc0e8de2f reverted).
The rest of the PR tries to reduce the runtime so make up for the delay introduced by the cluster reboot. In terms of speed, the end result is …
=> tests/cluster: Improve `fan` connectivity tests

bin/helpers, tests/storage-metadata
GH CI runners come with `yq` already installed, see [`ubuntu-22.04`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) and [`ubuntu-24.04`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md).
Yet, https://github.com/canonical/lxd-ci/actions/runs/14658595375/job/41138030832 shows that `yq` is installed:
```
Building dependency tree...
Reading state information...
jq is already the newest version (1.7.1-3build1).
The following additional packages will be installed:
python3-argcomplete python3-toml python3-xmltodict
The following NEW packages will be installed:
python3-argcomplete python3-toml python3-xmltodict yq
0 upgraded, 4 newly installed, 0 to remove and 25 not upgraded.
Need to get 80.6 kB of archives.
After this …
```
=> Be smarter when installing dependencies

README.md
Don't seed packages only used by lxd-imagebuilder.
=> README: streamline `lxd-ci` profile

.github/actions/image-test/action.yml
If test-image fails for an image, the built assets will be uploaded as CI artifacts for easier debugging.
Those assets are only uploaded on job retries or when the workflow is triggered manually. This avoids pilling up big assets in case a there is a problem with a distro.
=> github: allow debugging images that failed QA

images/opensuse.yaml
Fixes:
- Install dracut for thumbleweed images
- Fix sddm for desktop images
=> images/opensuse: Fix missing dracut package and sddm on desktop variant

tests/network-bridge-firewall
This is not strictly needed as the test scripts are not ran with `-o pipefail` so shouldn't fail even if `grep` doesn't find any match. Doing this now will make it simpler to use `-o pipefail` later on if we ever want.
=> tests/network-bridge-firewall: defensive check for br_netfilter presence

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml
Most distributions do not publish images during the weekends for obvious reasons so rebuilding/republishing those works against the local cache that LXD manages.
Closes https://github.com/canonical/lxd/issues/13294
=> github: don't build/publish images during the weekends

tests/storage-disks-vm
Provide the right instance name to `lxc info --show-log` and avoid the subshell.
=> tests/storage-disks-vm: fix debug logic

.github/workflows/image-openeuler.yml
Our CI runners building images are also located in the US.
=> github: use a US mirror to download openEuler

tests/storage-metadata
Since `backup/index.yaml` is at the begining of the archive:
```
$ tar -tzf v1.tar.gz
backup/index.yaml
backup/virtual-machine
backup/virtual-machine/backup.yaml
backup/virtual-machine/metadata.yaml
backup/virtual-machine/templates
backup/virtual-machine/templates/hostname.tpl
backup/virtual-machine.img
```
This should save some time reading/decompressing:
```
$ time tar -tzf v1.tar.gz backup/index.yaml
backup/index.yaml
real	0m15.132s
user	0m14.430s
sys	0m1.913s
$ time tar --occurrence=1 -tzf v1.tar.gz backup/index.yaml
backup/index.yaml
real	0m0.004s
user	0m0.001s
sys	0m0.003s
```
=> tests/storage-metadata: ask `tar` to stop scanning the archive when the needed file is found

tests/storage-metadata
This PR has an impact on the overall speed of the `storage-metadata` test but ensures the migrated instance can be started successfully.
=> Test: Extend `storage-metadata` and start the instance after migration

tests/network-routed
This mirrors what `tests/network-ovn` does.
It makes the script compatible with `ubuntu-minimal-daily:24.04` image like one would get:
```
$ lxc launch ubuntu-minimal-daily:24.04 v1 --vm -p lxd-ci
root@v1:~# cd lxd-ci/
root@v1:~/lxd-ci# ./bin/local-run tests/network-routed latest/edge
...
```
=> tests/network-routed: install iputils-ping if not present already

tests/cluster
Before this commit, one CI run failed with:
```
==> Upgrading the cluster
++ seq 3
+ for i in $(seq "${SIZE}")
+ lxc exec m1 -- snap wait system seed.loaded
+ lxc exec m1 -- snap refresh
2025-06-10T08:26:55Z INFO Waiting for "snap.lxd.daemon.service" to stop.
lxd 6.4-2336111 from Canonical** refreshed
+ lxc exec m1 -- snap changes
ID   Status  Spawn               Ready               Summary
1    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize system state
2    Done    today at 08:25 UTC  today at 08:25 UTC  Install "lxd" snap from "latest/stable" channel
3    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize device
4    Done    today at 08:26 UTC  today at 08:27 UTC  Refresh "lxd" snap
+ lxc exec m1 -- snap switch lxd --channel=latest/edge --cohort=+
"lxd" switched to …
```
=> tests/cluster: hold the LXD snap from the source channel

tests/devlxd-vm
In the name of the recent regression, this checks that the output from `/1.0/config/<key>` and `/1.0/meta-data` is properly formatted and is not escaped.
=> tests/devlxd: Test cloud-init and metadata output

.github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-funtoo.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml
Booting a container and a VM to run some basic tests should be relatively quick. We've seen a couple of failures where VMs would not reboot properly and burn the through the whole 6 hours limit imposed by GH.
=> github: set a timeout for running actions/image-test

tests/conversion
Removing the `passt` package fixes the issue:
```
PID file open: Permission denied
libguestfs: trace: v2v: launch = -1 (error)
virt-v2v-in-place: error: libguestfs error: passt exited with status 1
```
Thanks to @mihalicyn, we found that when `passt` package is present on the system, `virt-v2v` tries to use it to emulate networking for unprivileged namespaces. However, when there is no `passt` present, this part is simply skipped due to missing package.
passt: https://passt.top/passt/about/
=> tests/conversion: Remove passt package

.github/actions/image-upload/action.yml
The way we are handling the `inputs.target` is using a pattern subject to [template-injection](https://docs.zizmor.sh/audits/#template-injection) which should be avoided in the future, hence the FIXME. However, there is no security concern here so it's fine as it is.
=> Upload fix

tests/gpu-container
There's no snapshots or multiple instance launches.
Using ZFS prevents testing on older hosts without supported ZFS.
=> tests/gpu-container: No need to use ZFS here

tests/ui
* tests/ui: remove setting permissions flag, the flag is obsolete
=> tests/ui: remove setting permissions flag, the flag is obsolete

.github/actions/image-upload/action.yml
In the previous upload batch, multiple images failed to connect despite the 3 quick retries:
```
Thu, 24 Jul 2025 00:12:24 GMT + sftp -oHostKeyAlgorithms=ssh-ed25519 -P 922 -oConnectionAttempts=3 -oConnectTimeout=5 -b - imageserver@images.lxd.canonical.com
Thu, 24 Jul 2025 00:12:42 GMT ssh: connect to host images.lxd.canonical.com port 922: Connection timed out
Thu, 24 Jul 2025 00:12:42 GMT Connection closed
```
By spacing out the retries more and trying more time, hopefully, whatever connectivity hiccup we are facing will be shorter.
While 10 retries sounds a bit much, it's still quicker than the initial 135s of delay on connection failure and it is also much cheaper to retry the upload rather than re-run the whole workflow that builds the image again just to re-attempt the upload.
=> github: more aggressively retry SFTP uploads in `actions/images-upload`

.github/actions/image-upload/action.yml, .github/workflows/image-almalinux.yml, .github/workflows/image-alpine.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-archlinux.yml, .github/workflows/image-busybox.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-fedora.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml, .github/workflows/image-voidlinux.yml
This change does two things:
* Spread out the image building/publication to avoid overloading `images:`
* Build `arm64` images daily now that `arm64` runners are free
(addresses parts of https://github.com/canonical/lxd/issues/15651)
This should help with the SFTP upload we have especially on Sundays because `arm64` and `amd64` builds were triggered at the exact same time for all distros.
=> github: tweak image building/publication schedule

.github/workflows/image-almalinux.yml, .github/workflows/image-alt.yml, .github/workflows/image-amazonlinux.yml, .github/workflows/image-centos.yml, .github/workflows/image-debian.yml, .github/workflows/image-devuan.yml, .github/workflows/image-gentoo.yml, .github/workflows/image-kali.yml, .github/workflows/image-mint.yml, .github/workflows/image-nixos.yml, .github/workflows/image-openeuler.yml, .github/workflows/image-opensuse.yml, .github/workflows/image-openwrt.yml, .github/workflows/image-oracle.yml, .github/workflows/image-rockylinux.yml, .github/workflows/image-slackware.yml, .github/workflows/image-ubuntu.yml
This brings the `arm64` image offering on par with `amd64` except for VM images that we cannot test (no nested virt on `arm64` runners yet) so we don't build/ship. This will close https://github.com/canonical/lxd/issues/15651
All the known EOL dates were added while at it.
Thing to note: the Devuan images are the last ones being built on a 22.04 runners but the built and tested fine even with the `ubuntu-22.04-arm` runners.
=> Enable `arm64` images where possible

bin/helpers
This should address the occasional failure in `tests/network-ovn`:
```
+ snap install microovn --channel=latest/edge --cohort=+
error: cannot install "microovn": Post
"https://api.snapcraft.io/v2/snaps/refresh": context canceled
```
=> bin/helpers: wait for snapd to be seeded before interacting with it

tests/network-ovn
Follow-up to https://github.com/canonical/lxd/pull/16119.
Add tests to check that load balancers and forwards are reachable from inside the ovn network.
=> tests: Check that load balancers and forwards are reachable from inside the OVN network

.github/workflows/image-openwrt.yml
Fixes commit 2c041a48956d4896eb3793042669b4bf09814e91
=> github: quote strings ending with `0` as it rendered as `24.1`

.github/workflows/image-gentoo.yml, .github/workflows/image-slackware.yml
Slackware uses a separate site to distribute `arm64` builds so it would need
more work on lxd-imagebuilder.
=> Fix 2 issues with `arm64` images

tests/container-nesting
Test ZFS in nested containers using ZFS delegation.
This also required ZFS version >= `2.2`.
Note that `/dev/zfs` permissions are too strict, and we have a workaround in place to allow usage of ZFS inside the nested container.
=> tests: Test ZFS in nested containers

.github/actions/image-setup/action.yml
A `tcpdump` capture on the PS6 VM showed that failed upload were accompanied with exactly 0 traffic from GH reaching the PS6 VM. Since this traffic is subject to IP allow-lists, my current theory is that IS' list does not include an up to date list of GH possible IPv4 source addresses.
As such, it's best to test the connectivity before doing anything "expensive" with the GH runner. Also, when the connectivity will fail again, I'll be armed with the public IPv4 that was used for the upload test and this will let me correlate it with the allow-list maintained by IS.
=> github: do SFTP connectivity test in `actions/image-setup`

tests/network-ovn
This PR adds tests to check that internal load balancers and forwards are reachable from inside of the OVN network, but are unreachable from outside.
Follow-up to https://github.com/canonical/lxd/pull/16162.
This should be merged together with https://github.com/canonical/lxd/pull/16179 (adds `ovn_internal_load_balancer` API extension for LXD).
=> tests: Add tests for internal load balancers and forwards

tests/storage-vm
Only set the `storage.images_volume` if not testing with a remote storage driver whose volumes cannot be accessed concurrently.
LXD rightfully returns an error but the test should skip those which are not supported.
=> Tests: Exclude all remote block storage drivers for `images_volume`

tests/ui
- tests/ui: adjust to new ui test projects and setup
- UI test projects have been split into unclustered and clustered backend tests. Relying on the big unclustered suite for now. Leaving addition of setup and run of the clustered suites for a later iteration.
=> tests/ui: adjust to new ui test projects and setup

tests/gpu-container
=> tests/gpu-container: Only test CDI mode on LXD servers with CDI mode support

tests/container
Apparently images got bigger:
```
+ lxc exec n1 -- lxc launch ubuntu-minimal-daily:25.10 n11
Launching n11
Retrieving image: metadata: 100% (915.56MB/s)
Retrieving image: rootfs: 1% (1.84MB/s)
Retrieving image: rootfs: 1% (1.84MB/s)
Error: Failed instance creation: write /var/snap/lxd/common/lxd/images/4cc7daf415337cc9c972356d937ebb177ea7620ce6112bdbfd831b6d2c819ac2.rootfs: no space left on device
```
=> tests/container: use a larger loop dev

.github/workflows/image-busybox.yml
Busybox is released as a single tarball once in a blue moon and there are not package to update. The point of rebuilding/publishing new images is mostly to pick up new images quickly but that is such a rare event that we can do a manual build when that happens.
We could in theory stick to a single build and publish but we'll stick to a weekly cadence to avoid the images to be considered stale and expunged from `images:`.
This should reduce the pressure on the apparently overloaded download mirror.
=> github: move to a weekly build/publication cadence for `busybox`

tests/network-ovn
Logical Routers in OVN 22.03 do not support answering ARP requests for Load Balancer IP addresses that are not part of the subnet on one of their Logical Router Ports[0].
This makes some of the tests in the `forward` suite flaky, because these tests set up Load Balancers with external IP addresses that don't belong to any of the router subnets. As such, they rely on occasional left-over ARP entry for the LB IP to pass.
There's already an established precedent in the network-ovn test suites to add a host route for the Load Balancer IP via the IP address of the Logical Router Port.
This change adds the host routes in test suites where it was missing.
[0] https://github.com/ovn-org/ovn/issues/124
=> tests/network-ovn: Host route for LB external IPs

bin/helpers
As such, no need to explicitly check which is the current project.
Inspired by https://github.com/canonical/lxd/pull/16678/commits/f9c9a8e1182fe19f64c7a718f6af2606d06922ae
=> bin/helpers: using `--project ""` does the right thing
